# Final document

## Picking a final output doc

* After all our hard work to explore and polish a final plot we should show it off in an easy to navigate html document. Here are three good options I reccomend.

## flexdashboard

* This [Flexdashboard by Matt Dray](https://github.com/matt-dray/earl18-crosstalk) is a fantastic working example. It includes some of the interactivty we saw earlier using crosstalk, plotly and DT tables described in the earlier [Interactive plots] chapter.

* Also, here is an easy to follow tutorial presentation on [how to build flexdashboards](https://arm.rbind.io/slides/flexdashboard.html#1)

## R markdown with floating contents and tabbed sections

* When using R markdown I've found a [floating table of contents](https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents) and [tabbed sections](https://bookdown.org/yihui/rmarkdown/html-document.html#tabbed-sections) are the most effective for providing compact and easy to navigate html documents.

## bookdown

* Finally, how this book itself was created is suprisingly quick to do. Here is a board [bookdown guide](https://bookdown.org/home/about/) to follow. This is how I built this book:
 
1. Clone or download this [minimal example](https://github.com/rstudio/bookdown-demo).  

2. Add this line....

> `output_dir: "docs"` 
  
  ...to the configuration file `_bookdown.yml` (as described [here](https://bookdown.org/yihui/bookdown/github.html))
  
3. In RStudio build the book to gitbook format either using the drop down in the build tab (next to Environment tab), or by running  this line of code..
   
> `rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')`
 
  ...this builds the book into a single doc folder holding all the html files needed in it. 

4. Push the docs folder to your repo so it's ready to publish.

5. Now on GitHub website follow this [guidance](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site). It describes how you go to the `Settings` of the repo, then `GitHub Pages` section, then the `Source` section that has a drop down.
Select the third option of the Source drop down that is....
   
> `master branch/docs folder 
   Use only the docs folder for Github pages`
   
   ..it then has a bit of a think then tells you when the published book is ready to view and at what web address.