--- 
title: "Rapid R Data Viz Book"
author: "Bill Cockerill"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Description"
---

# Why read this?

## A rapid approach to data viz

* This is my *current* approach to data visualiation in R. My apporach keeps chaning. I'm amazed how often you can discover new methods and packages just in the excellent [R-Bloggers](https://www.r-bloggers.com/) website or [#rstats](https://twitter.com/search?q=%23rstats&src=typd&lang=en) on Twitter.

* No matter how expert you are using R I hope you learn about at least one new trick from this short guide. I always have in mind helping people just starting in R. Particularly anyone struggling to learn as I did. I love how the R community create many guides that de-mystify and democratise data analysis in R. With the same aim, all the code examples here are super simple and re-usable. As well as providing more complex examples set out clearly so they are easier to understand and re-use.

* Another reason forsuper simple examples is they can become fast Exploratory Data Exploration (EDA) methods too. The best data work starts with good EDA. That includes high quality data engineering or Kaggle Data Science competition winners.

## What about Python?

* Python is great for data visualisation too such as Pands, Seaborn, Matplotlib, and Bokeh. But my day to day work is in R only so that's where I've built most data vis skills so far. A good place to find similar examples with real data are Python Notebooks on the Kaggle Data Science website https://www.kaggle.com/kernels Use the filters at the top to select popular data visulisation notebooks in Python. 

## What about other tools? 

* Graphical User Interface (GUI) or Point and Click (PaC) tools like Excel, PowerBI and Tableau still have their place as long as we don't end up doing our data engineering with them. As Hadley wickham says... And even PowerPoint can be used to create publication quality charts.

## Find an R master to inspire you...

* I hope you will find this material inspires you to try some new techniques that make your work faster and more interesting. How David Robinson explores, cleans then analystes data in R is inspiring. Lots of tricks I use here I saw him do on his Tidy Tuesday YouTube videos. I describe these at bullet 18 in my this collection of good R guides: https://github.com/billster45/r-guides-and-galleries#putting-it-all-together

* Another R master, Claus Wilke has created a new guide similar to this in that it starts with simple examples that become more complex . In his practical guide see how he starts with the bare minimum code you need to create the plot then gradually builds it up into a publication quality plot: https://github.com/wilkelab/practicalgg He wrote this so that help make the charts he creates in Fundamentals of Data Visualization easier to copy: https://serialmentor.com/dataviz/

* This guide is similar to Wilke's but with a greater focus on EDA. I also offer a wider set of tools for EDA, particulary R packages that make your plot interactive. As well as describing my personal preference for writing R code in a very clean and structured style.